export enum RoutePath {
	Home = '/',
	Dashboard = '/dashboard',
	Profile = '/profile',
	Analytics = '/analytics',
	Inbox = '/inbox',
	Settings = '/settings',
	Login = '/login',
	Register = '/register',
	RegisterSubmit = '/register/submit',
	RegisterYourDetails = '/register/your-details',
	RegisterVisualIdentity = '/register/visual-identity',
	RegisterConnectSocials = '/register/connect-socials',
	Comic = '/comic',
	ComicUploadAssets = '/comic/upload-assets',
	ComicConnectSocials = '/comic/connect-socials',
	ComicIssue = '/comic-issue',
	CreateComicIssue = '/comic-issue/create',
	ComicIssueUploadCovers = '/comic-issue/upload-covers',
	ComicIssueUploadAssets = '/comic-issue/upload-assets',
	ComicIssueUploadPages = '/comic-issue/upload-pages',
	ComicIssuePublish = '/comic-issue/publish',
}
