export const RoutePath = Object.freeze({
	Home: '/',
	Dashboard: '/dashboard',
	Profile: '/profile',
	Analytics: '/analytics',
	Inbox: '/inbox',
	Settings: '/settings',
	Login: '/login',
	Register: '/register',
	RegisterSubmit: '/register/submit',
	RegisterYourDetails: '/register/your-details',
	RegisterVisualIdentity: '/register/visual-identity',
	RegisterConnectSocials: '/register/connect-socials',
	Comic: (comicSlug: string) => `/comic/${comicSlug}`,
	CreateComic: '/comic/create',
	EditComic: (comicSlug: string) => `/comic/${comicSlug}/edit`,
	ComicUploadAssets: (comicSlug: string) => `/comic/${comicSlug}/upload-assets`,
	ComicConnectSocials: (comicSlug: string) => `/comic/${comicSlug}/connect-socials`,
	ComicIssue: (comicIssueId: string | number) => `/comic-issue${comicIssueId}`,
	CreateComicIssue: (comicSlug: string) => `/comic-issue/create?comicSlug=${comicSlug}`,
	ComicIssueUploadCovers: (comicIssueId: string | number) => `/comic-issue/${comicIssueId}/upload-covers`,
	ComicIssueUploadAssets: (comicIssueId: string | number) => `/comic-issue/${comicIssueId}/upload-assets`,
	ComicIssueUploadPages: (comicIssueId: string | number) => `/comic-issue/${comicIssueId}/upload-pages`,
	ComicIssuePublish: (comicIssueId: string | number) => `/comic-issue/${comicIssueId}/publish`,
})
